### PR TITLE
Strip out file extensions from apis

### PR DESCRIPTION
**Pull request by eric-wieser**
Either this, or rename files to lose their extension (or both)

### CODE REVIEW

**Comment by damien** [comment]
If we're going to do this, can you make your API loader agnostic of the file extension? All installed files have the `lua` file extension removed, but it could be handy for running the source code directly.

Edit: here's the basic install process, for your benefit - https://github.com/damien/cc-scripts/blob/master/bootstrap.lua#L73-L95

**Comment by eric-wieser** [comment]
This is already extension agnostic - it turns `script.xyz` into `script` but leaves `script2` as is

**Comment by damien** [comment]
Awesome. I'll review this after I get some sleep, thanks for all the contributions!

**Comment by damien** [comment]
I added some white space and removed the explicit calls to the `t` API; other than that your changes are in!

**Pull request merged**
