### PR TITLE
Overrides the built in API functionality

### PR DESCRIPTION
**Pull request by eric-wieser**
Better named version of #3

### CODE REVIEW

**Comment by damien** [comment]
I dig it. Especially since I've been having a hell of a time inheriting from the turtle API with a wrapper I've been working on. Well done sir!

**Comment by eric-wieser** [comment]
There's another problem here. API files can't end with `.lua`, since that loads the API into `_G['t.lua']`, which is useless.

Make `loadAPI` strip the `.lua`, or rename files?

**Comment by damien** [comment]
@eric-wieser Don't you worry about it. The bootstrap/installer script downloads all the apis and programs and saves them while omitting the file extension.

**Comment by eric-wieser** [comment]
I missed that. Whoops!

Also, there's still a problem here: there's still no way for an API to set its metatable, as doing so would remove the lookup to _G. Also, as a side effect of the previous commits, this runs:

``` lua
os.loadAPI('myAPI')

print(myAPI.myAPI.myAPI.myAPI.myAPI.myAPI.myAPI.math)
```

More thought required, I fear.

**Comment by damien** [comment]
And down the rabbit hole we go! I'm short on sleep at the moment, but I'll see if I can hop into the CC IRC chat room and bug the developers about the API loading system they have set up. I get the impression they had something specific in mind and that I'm doing it wrong.

**Comment by eric-wieser** [comment]
I think the system is flawed in some way at the moment. I might hop on the chatroom myself once I've worked out an alternative.

Actually, the bug I describe above is [present in the builtin `module` function of standard lua](http://lua-users.org/wiki/LuaModuleFunctionCritiqued).

**Comment by eric-wieser** [comment]
Fixed in eric-wieser/cc-scripts@892eb51e5ca6c7b6fa1055402ead8c5fd354e99a

**Pull request merged**
